create table shipment_history (
    order_number bigint,
    first_name varchar(255),
    last_name varchar(255),
    company varchar(255),
    address1 varchar(255),
    address2 varchar(255),
    address3 varchar(255),
    address4 varchar(255),
    city varchar(255),
    state varchar(2),
    zip_code varchar(5),
    country varchar(2),
    email varchar(255),
    phone varchar(10),
    mail_class varchar(20),
    cart_items varchar(60000),
    shipment_dtm timestamp default current_timestamp,
    create_dtm timestamp default current_timestamp,
    notes varchar(500));